# This workflow will build a Java project with Maven
name: Java CI with Maven in Linux
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # test against several Java versions:
        java: [ 8, 11 ]
        # test against several OSes:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Build with Java ${{ matrix.java }}
    name: Build with Java on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: mvn -f it.lorenzopratesi.app.hotelsbooking/pom.xml clean verify